version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: arkanoid-db
    networks:
      - awesome

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/defined-arkanoid-13.ya-praktikum.tech/fullchain.pem:/etc/nginx/ssl/cert.pem
      - /etc/letsencrypt/live/defined-arkanoid-13.ya-praktikum.tech/privkey.pem:/etc/nginx/ssl/key.pem
    ports:
      - "80:80"
      - "443:443"

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:6.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge
